[workspace]
resolver = "3"
members = ["biometric"]

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
thiserror = "2"
cxx = "1"
autocxx = { git = "https://github.com/google/autocxx.git", branch = "main" }
autocxx-build = { git = "https://github.com/google/autocxx.git", branch = "main" }
serde = "1"
serde_json = "1"
anyhow = "1"

[workspace.lints.rust]
unsafe_code = "allow"

[workspace.lints.clippy]
nursery = "deny"
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
string_slice = "deny"
pedantic = "deny"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Debanjan Basu"]
description = "Am I a duck, am I a beaver? I'm a platypus!"
homepage = "https://platypus.github.io"
documentation = "https://platypus.github.io/docs"
