[unstable]
build-std = ["std", "panic_abort", "core", "alloc"]
build-std-features = ["panic_immediate_abort"]

[build]
rustflags = [
    "-Clto",
    "-Cembed-bitcode=yes",
    "-Clinker-plugin-lto",
    "-Zdylib-lto",
    "-Zlinker-features=+lld",
    "-Zvirtual-function-elimination",
    "-Zlocation-detail=none",
    "--cfg",
    "tokio_unstable",
]

# [profile.dev]
# panic = "abort"

[profile.release]
opt-level = "z"
debug = false
lto = true
codegen-units = 1
# panic = "abort"
strip = true
incremental = false

# Try to enable all the features for wasm32-unknown-unknown
# Use the following command to find the target-features
# rustc --target=wasm32-unknown-unknown --print=target-features
[target.wasm32-unknown-unknown]
rustflags = [
    "-C",
    # wide-arithmetic is not supported by wasm-bindgen as of yet - as it's support rust stable, not nightly
    # Cannot use +atomics as they are not supported by veilid yet - These require COEP, i.e. websocket connection to only the same domain
    # "target-feature=+atomics,+bulk-memory,+crt-static,+exception-handling,+extended-const,+multivalue,+mutable-globals,+nontrapping-fptoint,+reference-types,+relaxed-simd,+sign-ext,+simd128,+tail-call,+wide-arithmetic",
    "target-feature=+bulk-memory,+crt-static,+exception-handling,+extended-const,+multivalue,+mutable-globals,+nontrapping-fptoint,+reference-types,+relaxed-simd,+sign-ext,+simd128,+tail-call",
    "-C",
    "panic=abort",
    "-Zwasm-c-abi=spec",
]

[target.aarch64-apple-darwin]
rustflags = [
    # "-C",
    # "target-feature=+aes,+crc,+dit,+dotprod,+dpb,+dpb2,+fcma,+fhm,+flagm,+flagm2,+fp16,+frintts,+jsconv,+lor,+lse,+lse2,+neon,+paca,+pacg,+pan,+pmuv3,+ras,+rcpc,+rcpc2,+rdm,+sb,+sha2,+sha3,+ssbs,+v8.1a,+v8.2a,+v8.3a,+v8.4a,+vh",
    "-C",
    "panic=abort",
    "-Zpanic_abort_tests",
]

[target.aarch64-apple-ios-sim]
rustflags = [
    # "-C",
    # "target-feature=+aes,+crc,+dit,+dotprod,+dpb,+dpb2,+fcma,+fhm,+flagm,+flagm2,+fp16,+frintts,+jsconv,+lor,+lse,+lse2,+neon,+paca,+pacg,+pan,+pmuv3,+ras,+rcpc,+rcpc2,+rdm,+sb,+sha2,+sha3,+ssbs,+v8.1a,+v8.2a,+v8.3a,+v8.4a,+vh",
    "-C",
    "panic=abort",
    "-Zpanic_abort_tests",
]

[target.aarch64-apple-ios]
rustflags = [
    # "-C",
    # "target-feature=+aes,+crc,+dit,+dotprod,+dpb,+dpb2,+fcma,+fhm,+flagm,+flagm2,+fp16,+frintts,+jsconv,+lor,+lse,+lse2,+neon,+paca,+pacg,+pan,+pmuv3,+ras,+rcpc,+rcpc2,+rdm,+sb,+sha2,+sha3,+ssbs,+v8.1a,+v8.2a,+v8.3a,+v8.4a,+vh",
    "-C",
    "panic=abort",
    "-Zpanic_abort_tests",
]
