[package]
name = "biometric"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true

[dependencies]
swift-bridge = { workspace = true }
thiserror = { workspace = true }

# Dependencies for anything other than wasm
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true, default-features = false, features = [
    "sync",
    "macros",
    "io-util",
    "rt-multi-thread",
] } # Tokio with 'rt-multi-threaded' for others

# Dependencies for wasm
[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { workspace = true, default-features = false, features = [
    "sync",
    "macros",
    "io-util",
    "rt",
] } # Tokio with 'rt' for wasm32

[build-dependencies]
swift-bridge-build.workspace = true
tokio = { workspace = true, default-features = false, features = [
    "process",
    "macros",
    "rt-multi-thread",
] }
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true

[lints]
workspace = true
