[package]
name = "biometric"
edition = "2024"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
homepage.workspace = true

[dependencies]
tokio = { workspace = true, default-features = false, features = [
    "sync",
    "macros",
] }
thiserror = { workspace = true }
async-trait = { workspace = true }

# Dependencies whereing Swift caters for
[target.'cfg(target_vendor = "apple")'.dependencies]
swift-bridge = { workspace = true }

[build-dependencies]
swift-bridge-build.workspace = true
tokio = { workspace = true, default-features = false, features = [
    "process",
    "macros",
    "rt-multi-thread",
] }
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true

[lints]
workspace = true
