[unstable]
build-std = ["std", "panic_abort", "core", "alloc"]
build-std-features = ["panic_immediate_abort"]

[build]
rustflags = [
    "-Clto",
    "-Clinker-plugin-lto",
    "-Zdylib-lto",
    "-Zlinker-features=+lld",
    "-Zvirtual-function-elimination",
    "-Zlocation-detail=none",
    "--cfg",
    "tokio_unstable",
]

[profile.dev]
panic = "abort"

[profile.release]
opt-level = "z"
debug = false
lto = true
codegen-units = 1
panic = "abort"
strip = true
incremental = false

[target.aarch64-apple-darwin]
rustflags = [
    # "-C",
    # "target-feature=+aes,+crc,+dit,+dotprod,+dpb,+dpb2,+fcma,+fhm,+flagm,+flagm2,+fp16,+frintts,+jsconv,+lor,+lse,+lse2,+neon,+paca,+pacg,+pan,+pmuv3,+ras,+rcpc,+rcpc2,+rdm,+sb,+sha2,+sha3,+ssbs,+v8.1a,+v8.2a,+v8.3a,+v8.4a,+vh",
    "-C",
    "panic=abort",
    "-Zpanic_abort_tests",
]
